services:
  ytfetcher:
    build: .
    container_name: ytfetcher-bot
    env_file: .env
    environment:
      - DOWNLOAD_ROOT=/srv/ytfetcher/downloads
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - downloads:/srv/ytfetcher/downloads
      - certbot-www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    profiles: ["certbot"]
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot

volumes:
  downloads:
    driver: local
  certbot-www:
    driver: local
  certbot-etc:
    driver: local
